In [88]:
import pandas as pd

In [89]:
student_df =  pd.read_csv("cleaned_student_dataset.csv")

In [90]:
student_df.head()

,gender,highschool_grade,study_year,faculty,undergrad_2023,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent
0,Female,76.0,2nd Year,Arts & Social Sciences,72.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,Only weekends,8+,3,0,Yes,Yes,Very close
1,Male,89.0,2nd Year,Economic & Management Sciences,75.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,"Yes (NSFAS, etc...)",8+,Only weekends,3-5,4+,0,No,Yes,Very close
2,Male,76.0,1st Year,AgriSciences,55.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,2,8+,3,0,No,Yes,Very close
3,Male,89.0,2nd Year,Engineering,84.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,3-5,3,8+,2,0,Yes,Yes,Very close
4,Female,74.0,2nd Year,Arts & Social Sciences,52.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,Only weekends,5-8,1,3,No,Yes,Fair

## Grouping Categories

In [91]:
student_df.faculty.value_counts()

faculty
Economic & Management Sciences    200
Science                            55
Arts & Social Sciences             42
Engineering                        35
AgriSciences                       20
Medicine and Health Services       10
Law                                10
Education                           6
Name: count, dtype: int64

In [92]:
faculty_group = {
    "Science": "STEM",
    "Engineering": "STEM",
    "AgriSciences": "STEM",
    "Medicine and Health Services": "STEM",
    "Economic & Management Sciences": "Management",
    "Arts & Social Sciences": "Others",
    "Law": "Others",
    "Education": "Others"
}

In [93]:
student_df["faculty"] = student_df["faculty"].replace(faculty_group)

In [94]:
student_df["faculty"].value_counts()

faculty
Management    200
STEM          120
Others         58
Name: count, dtype: int64

In [95]:
# FOR gender
student_df.gender.value_counts()

gender
Male      205
Female    173
Name: count, dtype: int64

In [96]:
# for study_year
student_df.study_year.value_counts()

study_year
2nd Year        144
1st Year        115
Highschool       67
3rd Year         40
4th Year          7
Postgraduate      5
Name: count, dtype: int64

In [97]:
study_year_mapping = {
    "Highschool": "Junior",
    "1st Year": "Junior",
    "2nd Year": "Mid",
    "3rd Year": "Mid",
    "4th Year": "Senior",
    "Postgraduate": "Senior"
}

In [98]:
student_df["study_year"] = student_df["study_year"].map(study_year_mapping)

In [99]:
student_df.study_year.value_counts()

study_year
Mid       184
Junior    182
Senior     12
Name: count, dtype: int64

In [100]:
student_df

,gender,highschool_grade,study_year,faculty,undergrad_2023,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent
0,Female,76.0,Mid,Others,72.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,Only weekends,8+,3,0,Yes,Yes,Very close
1,Male,89.0,Mid,Management,75.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,"Yes (NSFAS, etc...)",8+,Only weekends,3-5,4+,0,No,Yes,Very close
2,Male,76.0,Junior,STEM,55.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,2,8+,3,0,No,Yes,Very close
3,Male,89.0,Mid,STEM,84.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,3-5,3,8+,2,0,Yes,Yes,Very close
4,Female,74.0,Mid,Others,52.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,Only weekends,5-8,1,3,No,Yes,Fair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,Male,85.0,Junior,Others,85.0,Unknown,R 5001 - R 6000,No,3-5,Only weekends,3-5,0,0,No,Yes,Very close
374,Female,74.0,Junior,STEM,74.0,Private accommodation/ stay with family/friends,Unknown,No,3-5,3,1-3,0,0,No,Yes,Close
375,Female,73.0,Mid,Management,58.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,"Yes (NSFAS, etc...)",5-8,1,8+,0,0,Yes,Yes,Very close
376,Male,85.0,Junior,Management,85.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,1-3,4+,5-8,4+,0,No,Yes,Close
377,Female,80.0,Junior,Management,63.0,Private accommodation/ stay with family/friends,R 5001 - R 6000,No,3-5,Only weekends,3-5,1,0,No,No,Close

In [101]:
student_df["accomodation"] = student_df["accomodation"].replace({
    "Private accommodation/ stay with family/friends" : "Private",
    "Non-private accommodation ie. Res " : "Public",
    "Unknown" :"Unknown"
    
})

In [102]:
student_df.accomodation.value_counts()

accomodation
Private                              316
Non-private accommodation ie. Res     43
Unknown                               19
Name: count, dtype: int64

In [103]:
# for allowance
student_df.allowance.value_counts()

allowance
R 4001- R 5000     142
R 5001 - R 6000     98
R 6001 - R 7000     56
R 7001 - R 8000     29
Unknown             27
R 8000+             26
Name: count, dtype: int64

In [104]:
allowance_map = {
    "Unknown": 5,
    "R 4001- R 5000": 0,
    "R 5001 - R 6000": 1,
    "R 6001 - R 7000": 2,
    "R 7001 - R 8000": 3,
    "R 8000+": 4
}

In [105]:
student_df["allowance"] = student_df["allowance"].map(allowance_map)

In [106]:
student_df.allowance.value_counts()

allowance
0    142
1     98
2     56
3     29
5     27
4     26
Name: count, dtype: int64

In [107]:
# for scholarship
student_df.scholarship.value_counts()

scholarship
No                     329
Yes (NSFAS, etc...)     43
Unknown                  6
Name: count, dtype: int64

In [108]:
student_df["scholarship"] = student_df["scholarship"].replace({
    "Yes (NSFAS, etc...)" : 0,
    "No" : 1  ,
    "Unknown" : 2
})

In [109]:
student_df.scholarship.value_counts()

scholarship
1    329
0     43
2      6
Name: count, dtype: int64

In [110]:
# for study hour
student_df.study_hours.value_counts()

study_hours
8+     110
3-5    100
1-3     76
5-8     73
0       19
Name: count, dtype: int64

In [111]:
study_hours_ = {
    "0": 0,
    "1-3": 1,
    "3-5": 2,
    "5-8": 3,
    "8+": 4
}

student_df["study_hours"] = student_df["study_hours"].replace(study_hours_)

In [112]:
student_df.study_hours.value_counts()

study_hours
4    110
2    100
1     76
3     73
0     19
Name: count, dtype: int64

In [113]:
# for party week
student_df.party_week.value_counts()

party_week
1                106
Only weekends    102
2                 78
3                 62
4+                15
0                 15
Name: count, dtype: int64

In [114]:
student_df["party_week"] = student_df["party_week"].replace({
    "0": 0,
    "1": 1,
    "Only weekends": 2,
    "2": 3,
    "3": 4,
    "4+": 5
})

In [115]:
student_df.party_week.value_counts()

party_week
1    106
2    102
3     78
4     62
5     15
0     15
Name: count, dtype: int64

In [116]:
# DRINKS NIGHT
student_df.drinks_night.value_counts()

drinks_night
5-8    104
3-5     85
1-3     85
8+      82
0       22
Name: count, dtype: int64

In [117]:

student_df["drinks_night"] = student_df["drinks_night"].replace({
     "0": 0,
    "1-3": 1,
    "3-5": 2,
    "5-8": 3,
    "8+": 4
})

In [118]:
student_df.drinks_night.value_counts()

drinks_night
3    104
2     85
1     85
4     82
0     22
Name: count, dtype: int64

In [119]:
# missed class
student_df.missed_classes.value_counts()

missed_classes
0     200
1      71
2      61
3      23
4+     23
Name: count, dtype: int64

In [120]:
student_df["missed_classes"] = student_df["missed_classes"].replace({
     "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4+": 4
})

In [121]:
student_df.missed_classes.value_counts()

missed_classes
0    200
1     71
2     61
3     23
4     23
Name: count, dtype: int64

In [122]:
# failed class
student_df.failed_classes.value_counts()

failed_classes
0     248
1      57
2      29
3      23
4+     21
Name: count, dtype: int64

In [123]:
student_df["failed_classes"] = student_df["failed_classes"].replace({
     "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4+": 4
})

In [124]:
student_df.failed_classes.value_counts()

failed_classes
0    248
1     57
2     29
3     23
4     21
Name: count, dtype: int64

In [125]:
# inrelationship
student_df.in_relationship.value_counts()

in_relationship
No     224
Yes    154
Name: count, dtype: int64

In [126]:
student_df["in_relationship"] = student_df["in_relationship"].replace({
    "Yes" : 0,
     "No": 1
})

In [127]:
student_df.in_relationship.value_counts()

in_relationship
1    224
0    154
Name: count, dtype: int64

In [128]:
# parent aprove
student_df["parent_approve"] = student_df["parent_approve"].replace({
    "Yes" : 0,
     "No": 1
})

In [129]:
student_df.parent_approve.value_counts()

parent_approve
0    333
1     45
Name: count, dtype: int64

In [130]:
# relation with parent
student_df.relation_parent.value_counts()

relation_parent
Very close    252
Close          93
Fair           32
Distant         1
Name: count, dtype: int64

In [131]:
student_df["relation_parent"] =  student_df["relation_parent"].replace({
    "Distant": 0,
    "Fair": 1,
    "Close": 2,
    "Very close": 3
})

In [132]:
student_df.relation_parent.value_counts()

relation_parent
3    252
2     93
1     32
0      1
Name: count, dtype: int64

In [133]:
student_df.faculty.value_counts()

faculty
Management    200
STEM          120
Others         58
Name: count, dtype: int64

In [134]:
student_df.head(10)

,gender,highschool_grade,study_year,faculty,undergrad_2023,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent
0,Female,76.0,Mid,Others,72.0,Private,0,1,4,2,4,3,0,0,0,3
1,Male,89.0,Mid,Management,75.0,Private,3,0,4,2,2,4,0,1,0,3
2,Male,76.0,Junior,STEM,55.0,Private,0,1,2,3,4,3,0,1,0,3
3,Male,89.0,Mid,STEM,84.0,Private,2,1,2,4,4,2,0,0,0,3
4,Female,74.0,Mid,Others,52.0,Private,0,1,2,2,3,1,3,1,0,1
5,Male,83.0,Junior,STEM,83.0,Private,2,1,4,5,2,3,1,0,0,3
6,Male,80.0,Mid,Management,54.0,Private,1,1,4,3,3,1,0,1,0,3
7,Female,85.0,Mid,Others,75.0,Private,1,1,2,4,2,2,0,0,0,3
8,Male,89.0,Junior,STEM,89.0,Unknown,1,1,4,2,2,0,0,1,0,3
9,Male,83.0,Junior,STEM,83.0,Unknown,2,1,2,4,3,4,0,1,0,2

In [135]:
student_df.to_csv("student_clean.csv", index=False)

# Encoding

In [136]:
# Target or Features
X = student_df.drop("undergrad_2023", axis =1 )
Y = student_df[["undergrad_2023"]]

In [137]:
X.dtypes

gender                  str
highschool_grade    float64
study_year              str
faculty                 str
accomodation            str
allowance             int64
scholarship          object
study_hours          object
party_week           object
drinks_night         object
missed_classes       object
failed_classes       object
in_relationship      object
parent_approve       object
relation_parent      object
dtype: object

In [138]:
from sklearn.preprocessing import OneHotEncoder

In [139]:
one_hot_encoder = OneHotEncoder(sparse_output= False)

In [140]:
pd.get_dummies(student_df, columns=["faculty"], dtype= int)

,gender,highschool_grade,study_year,undergrad_2023,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent,faculty_Management,faculty_Others,faculty_STEM
0,Female,76.0,Mid,72.0,Private,0,1,4,2,4,3,0,0,0,3,0,1,0
1,Male,89.0,Mid,75.0,Private,3,0,4,2,2,4,0,1,0,3,1,0,0
2,Male,76.0,Junior,55.0,Private,0,1,2,3,4,3,0,1,0,3,0,0,1
3,Male,89.0,Mid,84.0,Private,2,1,2,4,4,2,0,0,0,3,0,0,1
4,Female,74.0,Mid,52.0,Private,0,1,2,2,3,1,3,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,Male,85.0,Junior,85.0,Unknown,1,1,2,2,2,0,0,1,0,3,0,1,0
374,Female,74.0,Junior,74.0,Private,5,1,2,4,1,0,0,1,0,2,0,0,1
375,Female,73.0,Mid,58.0,Private,2,0,3,1,4,0,0,0,0,3,1,0,0
376,Male,85.0,Junior,85.0,Private,0,1,1,5,3,4,0,1,0,2,1,0,0
377,Female,80.0,Junior,63.0,Private,1,1,2,2,2,1,0,1,1,2,1,0,0

In [142]:
student_df.dtypes

gender                  str
highschool_grade    float64
study_year              str
faculty                 str
undergrad_2023      float64
accomodation            str
allowance             int64
scholarship          object
study_hours          object
party_week           object
drinks_night         object
missed_classes       object
failed_classes       object
in_relationship      object
parent_approve       object
relation_parent      object
dtype: object