## combining data from different sources into a single view

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    {"acc" : [1,2,3,4],
     "name": ["Ram", "Shyam", "Hari", "Ravi"],
     "age" : [21, 56,34,22]  
    }
)

In [9]:
df2 = pd.DataFrame(
    {"acc" : [1,2,3,4],
     "principle": [500,677,300,3056],
     "interest" : [4.5,6, 7.5,3.1]  
    }
)

In [10]:
df1

   acc   name  age
0    1    Ram   21
1    2  Shyam   56
2    3   Hari   34
3    4   Ravi   22

In [11]:
df2

   acc  principle  interest
0    1        500       4.5
1    2        677       6.0
2    3        300       7.5
3    4       3056       3.1

In [12]:
# joining these two dataset

## Concatenation

In [13]:
pd.concat([df1, df2], axis = 1)

   acc   name  age  acc  principle  interest
0    1    Ram   21    1        500       4.5
1    2  Shyam   56    2        677       6.0
2    3   Hari   34    3        300       7.5
3    4   Ravi   22    4       3056       3.1

## Merging

In [15]:
df1 = pd.DataFrame(
    {"key" : ["AB", "CB","AC", "DE"],
     "name": ["Ram", "Shyam", "Hari", "Ravi"],
     "age" : [21, 56,34,22]  
    }
)
df2 = pd.DataFrame(
    {"key" : ["AB", "CC","AC", "DF"],
     "principle": [500,677,300,3056],
     "interest" : [4.5,6, 7.5,3.1]  
    }
)

In [16]:
df1, df2

(  key   name  age
 0  AB    Ram   21
 1  CB  Shyam   56
 2  AC   Hari   34
 3  DE   Ravi   22,
   key  principle  interest
 0  AB        500       4.5
 1  CC        677       6.0
 2  AC        300       7.5
 3  DF       3056       3.1)

In [19]:
pd.merge(df1, df2, how = "inner",on = "key") #how =  inner, left, right,  outer joins, default = inner, on = key column

  key  name  age  principle  interest
0  AB   Ram   21        500       4.5
1  AC  Hari   34        300       7.5

In [20]:
pd.merge(df1, df2, how = "right",on = "key")

  key  name   age  principle  interest
0  AB   Ram  21.0        500       4.5
1  CC   NaN   NaN        677       6.0
2  AC  Hari  34.0        300       7.5
3  DF   NaN   NaN       3056       3.1

In [ ]:
# alternative -  df1.merge(df2)

# Joining 
combine based on their index