In [2]:
import pandas as pd

In [3]:
titanic_df = pd.read_csv("clean_titanic_dataset.csv")

In [4]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,initials
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,Mr

## Correlation
we can remove strong correlation columns

In [5]:
titanic_df.corr(numeric_only = True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin
PassengerId,1.000000,-0.007383,-0.038222,0.048647,-0.059846,-0.002111,0.013477,0.023808
Survived,-0.007383,1.000000,-0.347920,-0.071103,-0.037099,0.088546,0.263656,0.320768
Pclass,-0.038222,-0.347920,1.000000,-0.343128,0.081523,0.024483,-0.549743,-0.722195
Age,0.048647,-0.071103,-0.343128,1.000000,-0.271184,-0.204940,0.090824,0.231265
SibSp,-0.059846,-0.037099,0.081523,-0.271184,1.000000,0.416264,0.159262,-0.040342
Parch,-0.002111,0.088546,0.024483,-0.204940,0.416264,1.000000,0.197376,0.029055
Fare,0.013477,0.263656,-0.549743,0.090824,0.159262,0.197376,1.000000,0.478358
Cabin,0.023808,0.320768,-0.722195,0.231265,-0.040342,0.029055,0.478358,1.000000

### Chi Square Test - show dependency between categorical variables

In [6]:
import scipy.stats as stats

In [7]:
# contengency table
contengency_table =  pd.crosstab(titanic_df.Pclass, titanic_df.Survived)
contengency_table

Survived    0    1
Pclass
1          73  132
2          95   87
3         369  118

In [8]:
chi2_score, pvalue, dof, expected_frequency = stats.chi2_contingency(contengency_table)

In [9]:
chi2_score

np.float64(106.50830510958173)

In [10]:
print(f"p value = {round(pvalue, 5)}") # lower than significance level (0.05) so alternate hypothesis is true

p value = 0.0

In [11]:
dof

2

In [12]:
expected_frequency

array([[125.95537757,  79.04462243],
       [111.82379863,  70.17620137],
       [299.2208238 , 187.7791762 ]])

In [13]:
# contengency table
contengency_table =  pd.crosstab(titanic_df.Cabin, titanic_df.Parch)
contengency_table

Parch    0   1   2  3  4  5  6
Cabin
0      529  79  57  5  3  5  1
1      135  37  23  0  0  0  0

In [14]:
chi2_score, pvalue, _, _ = stats.chi2_contingency(contengency_table)

In [15]:
chi2_score

np.float64(13.584527241368798)

In [16]:
pvalue

np.float64(0.03463768792361963)

# Encoding 
 convert categorical columns into numerical ones so that they can be fitted by Ml models which only takes numerical data.

### Nominal - no order and Ordinal - has order or rank

## One Hot Encoding Technique -  equally importance to nominal data

In [17]:
pd.get_dummies(titanic_df, columns =["Sex", "Embarked"], dtype = int).head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,initials,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,0,Mr,0,1,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,1,Mrs,1,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,0,Miss,1,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,1,Mrs,1,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,0,Mr,0,1,0,0,1

## Label/ Target Encoding
Assigns a unique integer to each category (e.g., Low = 0, Medium = 1, High = 2)

In [18]:
import sklearn #library for data analysis

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
one_hot_encoder =  OneHotEncoder(sparse_output= False)

In [22]:
one_hot_encoder.fit_transform(
    titanic_df[["Sex"]]
)

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(874, 2))

In [23]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object)]

## Ordinal Data

In [24]:
# lets assume embark be ordinal data
titanic_df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
869    S
870    S
871    S
872    C
873    Q
Name: Embarked, Length: 874, dtype: str

In [25]:
# through pandas
titanic_df["encoded_embarked"],rule = pd.factorize(titanic_df.Embarked)

In [26]:
rule

Index(['S', 'C', 'Q'], dtype='str')

In [27]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,initials,encoded_embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C,Mrs,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S,Mr,0

In [28]:
# sklearn
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [29]:
ordinal_encoder =  OrdinalEncoder(dtype = int)

In [30]:
encoded_result = ordinal_encoder.fit_transform(titanic_df[["Embarked"]])

In [31]:
encoded_result

array([[2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [1],
       [2],
       [1],
       [1],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [1],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [1],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [0],
       [0],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1],
       [0],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [0],
       [1]])

In [32]:
ordinal_encoder.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [33]:
ordinal_encoder.inverse_transform(
    [[1],[2],[0],[1]]
)

array([['Q'],
       ['S'],
       ['C'],
       ['Q']], dtype=object)

In [34]:
final_df = titanic_df.drop(
    ["Name", "Ticket", "initials", "encoded_embarked"], axis= 1
)

In [35]:
final_df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,7.2500,0,S
1,2,1,1,female,38.0,1,0,71.2833,1,C
2,3,1,3,female,26.0,0,0,7.9250,0,S
3,4,1,1,female,35.0,1,0,53.1000,1,S
4,5,0,3,male,35.0,0,0,8.0500,0,S

In [36]:
# encoding categorical columns
onehot_encoder = OneHotEncoder(sparse_output=False)
ordinal_encoder = OrdinalEncoder(dtype = int)

In [37]:
age_embarked_encoded = onehot_encoder.fit_transform(titanic_df[["Sex", "Embarked"]])
pclass_encoded = ordinal_encoder.fit_transform(final_df[["Pclass"]])

In [38]:
final_df.Pclass = pclass_encoded

In [39]:
final_df = pd.get_dummies(final_df, columns=["Sex", "Embarked"], dtype=int)

In [40]:
final_df.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,2,22.0,1,0,7.2500,0,0,1,0,0,1
1,2,1,0,38.0,1,0,71.2833,1,1,0,1,0,0
2,3,1,2,26.0,0,0,7.9250,0,1,0,0,0,1
3,4,1,0,35.0,1,0,53.1000,1,1,0,0,0,1
4,5,0,2,35.0,0,0,8.0500,0,0,1,0,0,1

In [43]:
final_df.to_csv("encoded_titanic_dataset.csv", index = False)